version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - postgresdata: